### ISSUE TITLE
No connection on latest electrum version

### ISSUE THREAD

**Issue by Coinomatron** [vergecurrency/electrum#14]
Debug output as follows:

E/i | interface.[electrum.verge.dev:50002] | Exception in wrapper_func: UnsupportedAlgorithm('Backend object does not implement ScryptBackend.')
Traceback (most recent call last):
  File "/home/user/Downloads/electrumverge/electrum/electrum/util.py", line 988, in wrapper
    return await func(*args, **kwargs)
  File "/home/user/Downloads/electrumverge/electrum/electrum/interface.py", line 334, in wrapper_func
    return await func(self, *args, **kwargs)
  File "/home/user/Downloads/electrumverge/electrum/electrum/interface.py", line 358, in run
    await self.open_session(ssl_context)
  File "/home/user/Downloads/electrumverge/electrum/electrum/interface.py", line 465, in open_session
    await group.spawn(self.monitor_connection)
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/home/user/.local/lib/python3.7/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/home/user/Downloads/electrumverge/electrum/electrum/interface.py", line 501, in run_fetch_blocks
    self.mark_ready()
  File "/home/user/Downloads/electrumverge/electrum/electrum/interface.py", line 370, in mark_ready
    chain = blockchain.check_header(self.tip_header)
  File "/home/user/Downloads/electrumverge/electrum/electrum/blockchain.py", line 612, in check_header
    if b.check_header(header):
  File "/home/user/Downloads/electrumverge/electrum/electrum/blockchain.py", line 247, in check_header
    header_hash = hash_header(header)
  File "/home/user/Downloads/electrumverge/electrum/electrum/blockchain.py", line 86, in hash_header
    return hash_raw_header(serialize_header(header))
  File "/home/user/Downloads/electrumverge/electrum/electrum/blockchain.py", line 91, in hash_raw_header
    return hash_encode(getPoWHash(header_bytes))
  File "/home/user/Downloads/electrumverge/electrum/electrum/blockchain.py", line 38, in <lambda>
    getPoWHash = lambda x: Scrypt(salt=x, length=32, n=1024, r=1, p=1, backend=backend).derive(x)
  File "/home/user/anaconda3/lib/python3.7/site-packages/cryptography/hazmat/primitives/kdf/scrypt.py", line 29, in __init__
    _Reasons.BACKEND_MISSING_INTERFACE
cryptography.exceptions.UnsupportedAlgorithm: Backend object does not implement ScryptBackend.

**Comment by marpme** [comment]
Whichever type of operating system did you use and what OpenSSL version did you have? Also what do you mean with latest version?

**Comment by Coinomatron** [comment]
Ah yes, Ubuntu 16.04, OpenSSL 1.0.2p, from the main repo.
https://github.com/vergecurrency/electrum.git

**Comment by Coinomatron** [comment]
On a side note, I was wondering if this, if you don't specify a datadir with -D, it overwrites existing .electrum/ datafolders. If so, might be an idea to change the name.

**Comment by marpme** [comment]
You will need a at least OpenSSL 1.1 to run this version of electrum. Everything lower is also already discarded by OpenSSL themselves :) 

And actually it does create a new folder under „electrum-xvg“

**Comment by Coinomatron** [comment]
Hm. Since I have no need for an electrum wallet, I guess this was my testing contribution. Not going to manually install a second ssl version. Thanks for the answers, closing.
